schema_version: 1

context:
  name: caio
  version: "0.10.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/caio-${{ version }}.tar.gz
  sha256: 83b86d3c211ac585b979494848283443f3169d04ea9a0310dec2c9d577a1fba6

build:
  number: 0
  # requires-python is 3.10+
  # c.f. https://github.com/mosquito/caio/blob/bf8da967679914a8879501db386168bd8e3ece76/pyproject.toml#L11
  skip: match(python, "<3.10")
  script:
    - ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
  host:
    - pip
    - python
    - setuptools >=77
  run:
    - python

tests:
  - python:
      imports:
        - caio
      pip_check: true

about:
  summary: Asynchronous file IO for Linux Posix and Windows.
  license: Apache-2.0
  license_file: COPYING
  homepage: https://github.com/mosquito/caio

extra:
  recipe-maintainers:
    - thewchan
    - matthewfeickert
